# Generated by Django 5.0.6 on 2024-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='auth_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CODE_VERIFIED', 'CODE_VERIFIED'), ('DONE', 'DONE'), ('PHOTO', 'PHOTO')], default='NEW', max_length=128),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='auth_type',
            field=models.CharField(choices=[('VIA_EMAIL', 'VIA_EMAIL'), ('VIA_PHONE', 'VIA_PHONE')], default='VIA_EMAIL', max_length=128),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('ORDINARY_USER', 'ORDINARY_USER')], default='ORDINARY_USER', max_length=128),
        ),
    ]
